config/routes.rb
Omrails::Application.routes.draw do
  resources :cards


  devise_for :users

  get 'about' => 'pages#about'
  root :to => 'pages#home'
end

app/models/card.rb
class Card < ActiveRecord::Base
	attr_accessible :description, :image

	validates :description, presence: true
	validates :user_id, presence: true
	has_attached_file :image, styles: { medium: "320x240" }
	validates_attachment :image, presence: true,
	content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
	size: { less_than: 5.megabytes }

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable, 
  				:rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # GET /cards
  # GET /cards.json
  before_filter :authenticate_user!, except: [:index]
  def index
    @cards = Card.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = current_user.cards.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = current_user.cards.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = current_user.cards.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = current_user.cards.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = current_user.cards.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cards/_card.html.erb
<div class="box">
    <%= link_to (image_tag card.image(:medium)), card %>
    <p class="description">
        <%= card.description %>
    </p>
    <p>
        <strong>
            Posted by <%= card.user.name %>
        </strong>
    </p>
    <% if current_user == card.user %>
        <p>
          <%= link_to 'Edit', edit_card_path(card) %>
          <%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
    <% end %>
</div>

app/views/cards/_form.html.erb
<%= simple_form_for(@card, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
   <%= f.full_error :image_content_type, class: "alert alert-error" %>
  <%= f.input :image, label: "Upload Image" %>
  <%= f.input :description, as: :text, input_html: { rows: "3" } %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
    <div id="cards">
            <%= render @cards %>
        </div>

<br />

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<div class="row">
    <div class="span6 offset3">
        <div class="well">
          <%= image_tag @card.image %>
            <p>
              <%= @card.description %>
            </p>
            <p>
              <%= @card.user.name %>
            </p>
            <% if current_user == @card.user %>
            <%= link_to 'Edit', edit_card_path(@card)  %> |
            <%end%>
            <%= link_to 'Back', cards_path %>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <small>
    <%= link_to "Classalyze", "http://www.classalyze.com" %>
    by <%= link_to "Teer Design", "http://www.classalyze.com" %>
  </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">

			<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>

			<!-- Be sure to leave the brand out there if you want it shown -->
			<!-- <a class="brand" href="#"><%=image_tag("logo_cz.png")%></a> -->
			<%= link_to(image_tag("logo_cz.png", class: "brand"),root_path) %>
			<!-- Everything you want hidden at 940px or less, place within here -->
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li>
						<%= link_to "Home", root_path %>
					</li>
					<li> <%= link_to "About", about_path %> </li>
				</ul>
				<ul class="nav pull-right">
					<% if user_signed_in?%>
						<li> <%= link_to(image_tag("my_pic.jpg",:size => "25x25", class: "img-circle"), "#")  %> </li>
						<li> <%= link_to "Edit Profile", edit_user_registration_path %> </li>
						<li> <%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
					<% else %>
						<li> <%= link_to "Login", new_user_session_path %> </li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Classalyze</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
  <%= link_to "Classalyze", "http://www.classalyze.com" %> is an online analytics and reporting platform that integrates with the school system and analyzes test scores at a per concept level. Analysis in such a manner can provide meaningful insights into classroom and student performance.

</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
 <h1>Logged in!</h1>
<% else %>
  <div id="myCarousel" class="carousel slide">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <!-- Carousel items -->
    <div class="carousel-inner">
    	<div class="active item">
        <img src="assets/bg1_classalyze.jpg">
        <div class="carousel-caption">
          <div class="row">
            <div class="span12">
              <h1>Welcome to Classalyze</h1>
              <div class="row">
                <div class="span8">
                  Using Data to improve Classroom Performance
                  </div>
                  <div class="span2 offset 3">
                    <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-primary btn-large" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <div class="item">
        <img src="assets/bg2_classalyze.jpg">
        <div class="carousel-caption">
          <h1> Now working with Schools and NGOs</h1>
          <p>Please contact us at contact@teerdesign.com</p>
        </div>
      </div>
      <div class="item">
        <img src="assets/bg3_classalyze.jpg">
        <div class="carousel-caption">
          <h1> Brought to you by Teer Design</h1>
          <p>Teer Design's vision is to create tech products that positively impact society</p>
        </div>
      </div>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
  </div>
<%end%>
    <!-- ==========Hero Unit ====================
<div class="row">
<div class="hero-unit">
  <h1>Welcome to Classalyze</h1>
  <p>Using Data to improve Classroom Performance</p>
  <p>
    <%= link_to 'Sign Up', "#", class: "btn btn-primary btn-large" %> 
  </p>
</div> -->

<!-- ============= Grid System ================= -->
<!-- <div class="row">
  <div class="span8">
    <p>Using Data to improve Classroom Performance</p></div>
    <div class="span2 offset 2">
      <p><%= link_to 'Sign Up', "#", class: "btn btn-primary btn-large" %></p></div>
    </div> -->